feat: :sparkles: add title prop to icons
maevsi/maevsi pull request #861
Opened 2022-10-15 15:17 UTC by PhilGarb

- adds a container for icons that includes a title prop
- includes translations for titles

2022-10-15 18:52 UTC, dargmuesli requested changes
Thanks a ton for this tedious work! :fire: 
I've left a few translations that I think fit better. It was intelligent to use texts that relate to the current usage of those icons! They might be used in different contexts in the future though, so I've suggested some general translations.

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconAddressBook.vue
> +  title: Adress Book
```suggestion
  title: Adressbuch
en:
  title: Address book
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconDownload.vue
> +  title: Download
```suggestion
  title: Herunterladen
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconEnvelope.vue
> +  title: Invitations
```suggestion
  title: Umschlag
en:
  title: Envelope
```

We cannot be sure this icon will only be used for invitations in the future, so we should keep it general here and overwrite it if necessary.

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconExclamationCircle.vue
> +  title: Invalid
```suggestion
  title: Erroneous
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconEyeOff.vue
> +  title: Private
```suggestion
  title: Verstecken
en:
  title: Hide
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconInformationCircle.vue
> +  title: Invalid
```suggestion
  title: Information
en:
  title: Information
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconKey.vue
> +  title: Unlock
```suggestion
  title: Schlüssel
en:
  title: Key
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconListOl.vue
> +  title: Sortierte Liste
```suggestion
  title: Aufzählung
```

as recommended by @azolus.

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconListUl.vue
> +  title: Unsortierte Liste
```suggestion
  title: Liste
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconPaperPlane.vue
> +  title: Invitation
```suggestion
  title: Versenden
en:
  title: Send
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconParagraph.vue
> +  title: Paragraf
```suggestion
  title: Absatz
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconQrCode.vue
> +  title: QR Code
```suggestion
  title: QR-Code
en:
  title: QR code
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconSignOut.vue
> +  title: Sign-out
```suggestion
  title: Ausloggen
en:
  title: Sign out
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconUser.vue
> +  title: User
```suggestion
  title: Benutzer
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconUserTag.vue
> +  title: User Tag
```suggestion
  title: Benutzer-Tag
en:
  title: User tag
```

2022-10-15 18:52 UTC, dargmuesli commented on nuxt/components/icon/IconTelescope.vue
> +  title: Events
```suggestion
  title: Entdecken
en:
  title: Explore
```

2022-10-15 18:58 UTC, PhilGarb commented
Thank you for the quick review. I accepted your suggestions. I agree that more general translations do make sense, although there should probably be better title props passed from usage of the individual Icons. Since just hearing something like Envelope does not really mean much out of context.

2022-10-15 19:27 UTC, dargmuesli approved these changes

2022-10-15 21:18 UTC, merged

2022-10-17 03:51 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-17 04:23 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-17 04:38 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-17 04:55 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-18 00:16 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-18 00:24 UTC, dargmuesli commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-18 05:48 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-24 09:07 UTC, dargmuesli commented
:tada: This PR is included in version 0.147.0 :tada:

The release is available on [GitHub release](https://github.com/maevsi/maevsi/releases/tag/0.147.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: